Fix lywsd02 script
h4/lywsd02 pull request #23
Opened 2020-08-18 20:33 UTC by jacekkow

Sorry for the mistake - apparently I put a commit before amend for review.

2020-08-18 20:46 UTC, h4 requested changes

2020-08-18 20:46 UTC, h4 commented on scripts/lywsd02
> +import datetime
`from datetime import datetime` will be better

2020-08-18 20:46 UTC, h4 commented on scripts/lywsd02
> +import datetime
And replace `client.time = datetime.datetime.now()` with `client.time = datetime.now()`

2020-08-30 20:51 UTC, jacekkow commented
@h4: Changes were made as requested.

2020-09-02 08:49 UTC, merged